server:
  port: 8080
  context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.100.2:3308/sign?useUnicode=true&amp;characterEncoding=utf-8
    username: root
    password: shanghui
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true